insert into chart_song.singer (id, name) values (1, 'GiGi Nguyen');
insert into chart_song.singer (id, name) values (2, 'Zick Phạm');
insert into chart_song.singer (id, name) values (3, 'Vũ Duy Khánh');
insert into chart_song.singer (id, name) values (4, 'Đặng Tuấn Phương');
insert into chart_song.singer (id, name) values (5, 'Noo Phước Thịnh');
insert into chart_song.singer (id, name) values (6, 'Phương Trinh Jolie');
insert into chart_song.singer (id, name) values (7, 'So Hi');
insert into chart_song.singer (id, name) values (8, 'The Wings');
insert into chart_song.singer (id, name) values (9, 'Tuấn Cry');
insert into chart_song.singer (id, name) values (10, 'Quang Anh Rhyder');
insert into chart_song.singer (id, name) values (11, 'Amy Luong');
insert into chart_song.singer (id, name) values (12, 'ERIK');
insert into chart_song.singer (id, name) values (13, 'Hồ Quang Hiếu');
insert into chart_song.singer (id, name) values (14, 'Đen');
insert into chart_song.singer (id, name) values (15, 'Gin Tuấn Kiệt');
insert into chart_song.singer (id, name) values (16, 'Ưng Hoàng Phúc');
insert into chart_song.singer (id, name) values (17, 'Kay Trần');
insert into chart_song.singer (id, name) values (18, 'Yong Anhh');
insert into chart_song.singer (id, name) values (19, 'Linh Cáo');
insert into chart_song.singer (id, name) values (20, 'Anie Như Thùy');
insert into chart_song.singer (id, name) values (21, 'Chi Pu');
insert into chart_song.singer (id, name) values (22, 'Tiên Tiên');
insert into chart_song.singer (id, name) values (23, 'Đông Nhi');
insert into chart_song.singer (id, name) values (24, 'Nguyễn Trọng Tài');
insert into chart_song.singer (id, name) values (25, 'Uyên Linh');
insert into chart_song.singer (id, name) values (26, 'Bùi Anh Tuấn');
insert into chart_song.singer (id, name) values (27, 'B-Ray');
insert into chart_song.singer (id, name) values (28, 'Mcee Blue');
insert into chart_song.singer (id, name) values (29, 'Adam Lâm');
insert into chart_song.singer (id, name) values (30, 'Bảo Anh');
insert into chart_song.singer (id, name) values (31, 'Hồ Ngọc Hà');
insert into chart_song.singer (id, name) values (32, 'Xesi');
insert into chart_song.singer (id, name) values (33, 'Hoàng Tôn');
insert into chart_song.singer (id, name) values (34, 'Tăng Phúc');
insert into chart_song.singer (id, name) values (35, 'Trương Thảo Nhi');
insert into chart_song.singer (id, name) values (36, 'Bùi Lan Hương');
insert into chart_song.singer (id, name) values (37, 'Hari Won');
insert into chart_song.singer (id, name) values (38, 'SunD');
insert into chart_song.singer (id, name) values (39, 'Chí Thiện');
insert into chart_song.singer (id, name) values (40, 'Avin Lu');
insert into chart_song.singer (id, name) values (41, 'Thu Minh');
insert into chart_song.singer (id, name) values (42, 'Vương Anh Tú');
insert into chart_song.singer (id, name) values (43, 'Minh Vương M4U');
insert into chart_song.singer (id, name) values (44, 'Đạt G');
insert into chart_song.singer (id, name) values (45, 'Da LAB');
insert into chart_song.singer (id, name) values (46, 'Isaac');
insert into chart_song.singer (id, name) values (47, 'Mr. A');
insert into chart_song.singer (id, name) values (48, 'Hoàng Thùy Linh');
insert into chart_song.singer (id, name) values (49, 'Mai Tiến Dũng');
insert into chart_song.singer (id, name) values (50, 'Trang Hàn');
insert into chart_song.singer (id, name) values (51, 'Thảo Trang');
insert into chart_song.singer (id, name) values (52, 'MONSTAR');
insert into chart_song.singer (id, name) values (53, 'Soobin Hoàng Sơn');
insert into chart_song.singer (id, name) values (54, 'Khởi My');
insert into chart_song.singer (id, name) values (55, 'Sĩ Thanh');
insert into chart_song.singer (id, name) values (56, 'Lý Tuấn Kiệt (HKT)');
insert into chart_song.singer (id, name) values (57, 'Phạm Anh Duy');
insert into chart_song.singer (id, name) values (58, 'Thái Vũ (BlackBi)');
insert into chart_song.singer (id, name) values (59, 'Thanh Hưng Idol');
insert into chart_song.singer (id, name) values (60, 'Châu Khải Phong');
insert into chart_song.singer (id, name) values (61, 'Andiez');
insert into chart_song.singer (id, name) values (62, 'Reddy (Hữu Duy)');
insert into chart_song.singer (id, name) values (63, 'Trúc Nhân');
insert into chart_song.singer (id, name) values (64, 'Hoài Lâm');
insert into chart_song.singer (id, name) values (65, 'MIN');
insert into chart_song.singer (id, name) values (66, 'Tiêu Châu Như Quỳnh');
insert into chart_song.singer (id, name) values (67, 'Hà Nhi');
insert into chart_song.singer (id, name) values (68, 'Anh Tú');
insert into chart_song.singer (id, name) values (69, 'Vy Oanh');
insert into chart_song.singer (id, name) values (70, 'Charles Huỳnh');
insert into chart_song.singer (id, name) values (71, 'Lê Thiện Hiếu');
insert into chart_song.singer (id, name) values (72, 'EmD');
insert into chart_song.singer (id, name) values (73, 'Chi Dân');
insert into chart_song.singer (id, name) values (74, 'LK');
insert into chart_song.singer (id, name) values (75, 'Trịnh Đình Quang');
insert into chart_song.singer (id, name) values (76, 'Hamlet Trương');
insert into chart_song.singer (id, name) values (77, 'Phùng Khánh Linh');
insert into chart_song.singer (id, name) values (78, 'Đào Bá Lộc');
insert into chart_song.singer (id, name) values (79, 'Sơn Tùng M-TP');
insert into chart_song.singer (id, name) values (80, 'Phan Mạnh Quỳnh');
insert into chart_song.singer (id, name) values (81, 'Huỳnh James');
insert into chart_song.singer (id, name) values (82, 'Quang Vinh');
